config/routes.rb
AtlrugWebsite::Application.routes.draw do
  resources :suggestions, :only => [:index, :new, :create]

  resources :helps

  mount RailsAdmin::Engine => '/adminsrb', :as => 'rails_admin'

  devise_for :users

  get "talks/checklist" => "talks#checklist"

  resources :talks

  post "/newsletter" => "newsletter#subscribe", as: :subscribe

  match "/people"   => "about#people",   as: :people
  match "/projects" => "about#projects", as: :projects
  match "/join-us"  => "about#join_us",  as: :join_us

  root :to => "about#index"
end

app/models/affiliation.rb
class Affiliation < ActiveRecord::Base
  attr_accessible :dude, :project

  belongs_to :dude
  belongs_to :project
end

app/models/dude.rb
class Dude < ActiveRecord::Base
  attr_accessible :name, :email, :bio, :website,:ruby_gems_id
  attr_accessible :featured, :twitter, :github, :image_url

  habtm :projects, :join_table => :affiliations

  validates_presence_of :name
  # our migrations are so stupid. If we nuke the data, this conditional can go
  validates_presence_of :ruby_gems_id,
    :if => proc { |u| u.respond_to? :ruby_gems_id }

  scope :featured, where(featured: true)
  scope :regular, where(featured: false)

  before_save :set_avatar, if: Proc.new { |user|
    user.respond_to?(:twitter_changed?) and user.twitter_changed?
  }

  def bio
    bio = self['bio']

    bio.present? ? bio : "..."
  end

  def update_avatar!
    set_avatar
    save
  end

  def set_avatar
    if missing_image?
      twitter_response = get_twitter_info if twitter
      image_url = if twitter_response
        twitter_response["profile_image_url"].gsub(/normal/i, "bigger")
      else
        "missing_image.png"
      end
      self.image_url = image_url
    end
  end

  def missing_image?
    image_url.blank? || image_url == "missing_image.png"
  end

  def get_twitter_info
    response = HTTParty.get(
      "https://api.twitter.com/1/users/show.json?screen_name=#{self.twitter}")
    if response.code == 200
      response.parsed_response
    else
      false
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :url, :description

  habtm :dudes, :join_table => :affiliations

  validates_presence_of :name
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  attr_accessible :title, :suggester

  validates :title, :presence => true
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :title, :description, :presenter, :kind, :email
  attr_accessible :completed, :scheduled_date

  TALK_KINDS = %w(beginner intermediate advanced lightning)

  scope :by_kind, :order => "scheduled_date IS NULL,
                             scheduled_date,
                             CASE kind WHEN 'beginner'     THEN 1
                                       WHEN 'intermediate' THEN 2
                                       WHEN 'advanced'     THEN 3
                                       WHEN 'lightning'    THEN 4
                             END,
                             presenter,
                             title"

  def self.available
    by_kind.where(
      "completed = ? and (scheduled_date is NULL or scheduled_date < ?)",
      false,
      28.days.from_now)
  end

  validates(:kind,
            :inclusion => {
                           :in => TALK_KINDS,
                           :message => "%{value} is not a valid talk kind"
                          })
  validates :title, :presenter, :email, :presence => true

  def scheduled?
    self.scheduled_date
  end

  def kind_enum
    TALK_KINDS
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :remember_me

  devise(:database_authenticatable,
         :recoverable,
         # :confirmable,  # TODO: figure out email on heroku
         # :registerable, # TODO: figure out email on heroku
         :rememberable,
         :trackable,
         :validatable)
end

app/models/zenspider_subscriber.rb
class ZenspiderSubscriber
  include HTTParty
  base_uri 'lists.zenspider.com/mailman'

  class << self
    def subscribe!(options)
      subscribe_to_discussion options[:person] if options[
        :subscribe_to_discussion]
      subscribe_to_jobs options[:person] if options[:subscribe_to_jobs]
    end

    private

    def subscribe_to_discussion(person)
      post "/subscribe/ruby", query: person
    end

    def subscribe_to_jobs(person)
      post "/subscribe/rubyjobs", query: person
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @title = "Home"
  end

  def people
    @people = Dude.order('featured desc, name asc')
  end

  def projects
    @projects = Project.find(:all).sort_by { |p| p.name.downcase }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # filter_parameter_logging :password
  helper :all
  protect_from_forgery with: :exception
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController
  def subscribe
    ZenspiderSubscriber.subscribe!(params[:subscribe])
    redirect_to join_us_path
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  # GET /suggestions
  def index
    @suggestions = Suggestion.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /suggestions
  def create
    @suggestion = Suggestion.new(params[:suggestion])

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to suggestions_path,
          notice: 'Suggestion was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_filter :verify_password, :only => :create
  before_filter :set_title, :only => [:index, :create]

  def index
    talks
    @talk  = Talk.new
  end

  def create
    @talk = Talk.new(params[:talk])

    if @talk.save
      redirect_to talks_url, notice: 'Talk was successfully created.'
    else
      talks
      render action: "index"
    end
  end

  def checklist
  end

  private

  def set_title
    @title ||= "Talks"
  end

  def talks
    @talks ||= Talk.available
  end

  def verify_password
    unless params[:password] == "" then
      sleep rand(10) unless Rails.env.test?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitter_image(twitter_handle)
    "https://api.twitter.com/1/users/profile_" +
    "image?screen_name=#{twitter_handle}&size=bigger"
  end

  def icon_link icon, text, uri, uri_prefix=nil
    return if uri.blank?

    "<li><i class='#{icon}'></i>#{link_to text, "#{uri_prefix}#{uri}"}</li>"
  end

  def rubygems_link person
    icon_link("icon-heart", "Ruby Gems",
              person.ruby_gems_id, "http://rubygems.org/profiles/")
  end

  def github_link person
    icon_link "icon-glass", "Github", person.github
  end

  def website_link person
    icon_link "icon-user", "Website", person.website
  end

  def email_link person
    icon_link "icon-envelope", "Email", person.email, "mailto:"
  end

  def twitter_link person
    v = person.twitter
    icon_link "icon-leaf", "@#{v}", v, "http://twitter.com/"
  end

  def nav_item_link link_label, link_path
    content_tag :li, link_to(link_label, link_path),
      :class => ('active' if current_page?(link_path))
  end

  def title_or_action
    @title ||= params[:action].humanize
  end
end

app/helpers/talks_helper.rb
module TalksHelper
  def indefinite_Articlerize word
    word =~ /^[ai]/ ? "An #{word}" : "A #{word}"
  end

  def talk_kinds
    [["Talk Type", ""]] + Talk::TALK_KINDS.map { |k| [k.capitalize, k] }
  end
end

app/views/about/_maps.html.erb
<div class='row'>
  <div id="map" class='span12'>
    <div id="address" class='span4'>
      <h1>Monthly Meetup</h1>
      <table>
        <tr>
          <td><i class='icon-time'></i></td>
          <td><h3><time>7:00p</time> to <time>9:00p</time> Second Wednesday of the Month</h3></td>
        </tr>
        <tr>
          <td><i class='icon-map-marker'></i></td>
          <td>
            <address>
              <h3>Centergy Building</h3>
              75 5th St NW, Third floor, Hodges Room,<br />
              Atlanta, GA 30308
            </address>
          </td>
        </tr>
      </table>

      <h2> Scheduled Speakers </h2>

      <p><%= link_to "Please sign up to give a talk", talks_path %>.

      <p> TBA </p>

      <p> AL: MISSING MAP BELOW ************************************************** </p>

    <div class='span8'>
      <iframe height="200" frameborder="" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=75+5th+St+NW,+,+Atlanta,+GA&hl=en&sll=34.044983,-84.340347&sspn=0.243512,0.500565&hnear=75+5th+St+NW,+Atlanta,+Fulton,+Georgia+30308&t=m&z=17;output=embed"></iframe>
    </div>
  </div>
</div>

app/views/about/_twitter.html.erb
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/about/index.html.erb
<div class="row hero-unit">
  <%= image_tag 'seattle_rb_logo_big.png', id: "hero-ruby", class: "span2" %>
  <div id='hero-text' class='span9'>
    <h1>ATLRUG</h1>
    <h2>Atlanta Ruby User Group</h2>
    <p>
      AL: Remember above logo. **************************************************

      ATLRUG was the first Ruby and Rails user group in North America and has met regularly for over a decade. We convene every second Wednesday night to teach and learn about Ruby and Rails. All skill levels are welcome!
    </p>

    <a href="https://twitter.com/atlrug" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @atlrug</a>

    <%= render "twitter" %>
  </div>
</div>

<div class="row-fluid">
  <div class="span4">
    <h2>Why ATLRUG?</h2>
     <p>
       AL: REPLACE THIS TEXT WITH OUR TEXT. **************************************************

The Ruby and Rails worlds are known for their collaboration, and ATLRUG takes an active role. We focus on fun and collaborate to solve problems. We provide each other support as we take on new challenges in Ruby. We're proud to be the home of some of the <%= link_to "best Ruby developers around", people_path %>. Check out <a href='http://www.youtube.com/watch?v=ICVdf4WidkY'>this video</a> about our humble beginnings.
     </p>
  </div>
  <div class="span4">
    <h2>How Can I Participate?</h2>
    <p>
      AL: REPLACE THIS TEXT WITH OUR TEXT>. **************************************************
       
      The Tuesday "Nerd Club" is informal - drop in and code with us as you please. We also host larger, formal events on a semi-regular basis. We encourage everyone, from Ruby novice to expert, to join us to learn and contribute. We're excited to grow and support the Ruby and Rails communities.
    </p>
    <p>
      Most importantly: <%= link_to "Join us", join_us_path %> and <%= link_to "Sign up to give a talk", talks_path %>!
    </p>
 </div>
  <div class="span4">
    <h2>Where Can I Get Help?</h2>
    <p>
      The nicest thing about our members is the number of projects and resources we've helped grow. View our <%= link_to "projects", projects_path %>, join our <%= link_to "mailing list", join_us_path %>, follow us on <a href='http://twitter.com/atlrug'>twitter</a>, and peruse or submit to our <%= link_to "Atlanta jobs board", join_us_path %>.
    </p>
  </div>
</div>

<%= render :partial => "about/maps" %>

app/views/about/join_us.html.erb
<div class='join-us row'>
  <div class='span8'>
    <div id='map'>
      <h2>When & Where?</h2>
      <p>Come join us!

      <p>
        We have a monthly social on the first Tuesday of every month.
        Food, Beer, and Talks. <%= link_to "Sign up to give a talk", talks_path %>.
        Contact us if you want to sponsor or help organize a monthly
        event.
      </p>

      <p>
        We have a free-form hack night at Vivace Café every Tuesday
        (except the first) from 7-9 p.m. Bring whatever you’re working
        on, grab a cup of coffee, and meet other Rubyists. Everyone is
        welcome!
      </p>

      <p>
        <a href="https://twitter.com/atlrug" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @atlrug</a>
        
        <%= render "twitter" %>
      </p>
    </div>
  </div>
  <div id='newsletter' class='span4'>
    <h2>Join the Mailing Lists</h2>
    
    <p> These are low-volume and spam-free.</p>

    <%= form_tag subscribe_path do %>
      <div class="control-group">
        <%= label_tag 'subscribe[person][email]', "Email", class: "inline" %>
        <%= text_field_tag 'subscribe[person][email]', "", placeholder: "joe@example.com" %>
      </div>
      <div class="control-group">
        <%= check_box_tag "subscribe[subscribe_to_discussion]", 1, true %>
        <%= label_tag "subscribe[subscribe_to_discussion]", "Subscribe to Ruby Discussion" %>
        <br />
        <%= check_box_tag "subscribe[subscribe_to_jobs]", 1, true %>
        <%= label_tag "subscribe[subscribe_to_jobs]", "Subscribe to Ruby Jobs" %>
      </div>
      <%= submit_tag "Subscribe", class: 'btn' %>
    <% end %>
  </div>
</div>

<%= render :partial => "about/maps" %>

app/views/about/people.html.erb
<% @people.each do |person| %>
  <div class='featured profile row'>
    <div class='span1'>
      <%= image_tag person.image_url %>
    </div>
    <div class="span10 description">
      <h1 id="<%= person.name.parameterize %>"><%= person.name %></h1>
      <p class='bio'><%= person.bio %></p>

      <ul class='links'>
        <%= raw rubygems_link person %>
        <%= raw github_link   person %>
        <%= raw twitter_link  person %>
        <%= raw website_link  person %>
        <%= raw email_link    person %>
      </ul>

      <%#
         projs = person.projects.sort_by { |p| p.name.downcase }.map { |p|
           link_to p.name, p.url
         }
       %>

      <%# raw projs.join ", " %>

    </div>
  </div>
<% end %>

app/views/about/projects.html.erb
<p class="lead">
  <%= @projects.size %> projects from just <%= Dude.count %> people...
  <%= ["Not bad!", "How prolific!", "I've seen better..."].sample %>
</p>

<% @projects.each do |project| %>
  <div class='row project'>
    <div class='span10'>
      <h2><%= link_to project.name, project.url %></h2>
      <%= project.description %>
      <h3>Authors</h3>
      <ul class='links'>
        <% project.dudes.each do |dude| %>
          <li><%= link_to dude.name, "/people##{dude.name.parameterize}" %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>ATLRUG | <%= title_or_action %></title>
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

<nav class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "ATLRUG", root_path, class: 'brand' %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <%= nav_item_link "People", people_path %>
          <%= nav_item_link "Projects", projects_path %>
          <%= nav_item_link "Join Us", join_us_path %>
          <%= nav_item_link "Talks", talks_path %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</nav>

<div role="main" class='container'>
  <% if notice then %><p class="text-warning notice"><%= notice %></p><% end %>
  <% if alert then %><p class="text-error alert"><%= alert %></p><% end %>

  <%= yield %>
</div>
<footer>
  Atlanta Ruby User Group: Growing the Ruby Community
</footer>
<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :your_name %><br />
    <%= f.text_field :suggester %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestions/index.html.erb
<h1>Talk Topic Suggestions</h1>
This is a list of topics and questions that people in ATLRUG would like to have addressed at our monthly talk meetings.
<br/>
<br/>
<table style="margin-left: 10px;">
  <tr>
    <th style="text-align: left; font-size: 16px">Topic</th>
    <th style="text-align: left; font-size: 16px">Suggested By</th>
  </tr>

<% @suggestions.each do |suggestion| %>
  <tr>
    <td><%= suggestion.title %></td>
    <td><%= suggestion.suggester %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Suggestion', new_suggestion_path, {:style => 'margin-left: 10px'}%> 

app/views/suggestions/new.html.erb
<h1>New suggestion</h1>

<%= render 'form' %>

<%= link_to 'Back', suggestions_path %>

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :presenter,   :placeholder => "Name"                    %><br />
    <%= f.text_field :email,       :placeholder => "Email (private!)"        %><br />
    <%= f.text_field :title,       :placeholder => "Title"                   %><br />
    <%= f.text_area  :description, :placeholder => "Description", :rows => 3 %><br />
    <%= f.select :kind, talk_kinds %>

    <%= hidden_field_tag :password, "" %>

    <%= f.submit %>
  </div>
<% end %>

app/views/talks/checklist.html.erb
<ol>
  <li>
    Communicate with Patrick about speakers. Get names, photos, talk
    titles, and talk descriptions. He will make sure that Atlrug.org is
    updated, so one less thing for you to worry about!
  </li>

  <li>
    AL: CHANGE THIS TEXT **************************************************

    Set up an Eventbrite page. Eventbrite is free for free events. Cap
    it at 45, unless Ryan says otherwise.
  </li>

  <li>
    Promote the event!

    <ul>
      <li><%= link_to "ATLRUG list", "mailto:atlrug.giveback@gmail.com" %></li>
      <li><%= link_to "Meetup", "http://www.meetup.com/atlantaruby/" %></li>
      <li> etc...</li>
    </ul>
  </li>

  <li>
    AL: CHANGE THIS TEXT **************************************************

    Get food and eating implements. I ordered pick up
    from <a href="http://www.bigmariosnewyorkpizza.com/">Mario's
    Pizza</a>, a block away, and that was easy. Probably 10-12 8-slice
    pizzas. If there's a higher turnout, adjust accordingly.

    <p class="text-info">TODO: What is "higher turnout" ?</p>

    <p class="text-error">TODO: bluebox is in for $200. 10 pizzas are at least 170. Beer is 90... this math doesn't work.</p>
  </li>

  <li>
    AL: CHANGE THIS TEXT **************************************************

    Get beer and cups. I got a pony keg
    from <a href="http://www.elysianbrewing.com/">Elysian</a> (also
    within walking distance, but a pain to carry a keg from if
    walking). It runs about $90, plus a $150 refundable deposit when
    you bring the keg back. I think either that or canned/bottled beer
    would be fine - we didn't finish it.
  </li>

  <li>
    AL: CHANGE THIS TEXT **************************************************

    Ping <a href="pete@peterhiggins.org">Pete Higgins</a>, who is the
    contact at Substantial, about setup and/or anything else related
    to the venue.

    <p>Backup: <a href="mailto:aja@substantial.com">Aja Hammerly</a>.</p>
  </li>

  <li>
    AL: CHANGE THIS TEXT **************************************************

    Get there a little early to set up chairs, food/bev, and get a
    sign on the door.
  </li>

  <li>
    You got yourself a party!
  </li>

  <li>
    Let the sponsor know of your expenses for reimbursement.
  </li>
</ol>

app/views/talks/index.html.erb
<div class="row-fluid">
  <div class="span4">
    <h1>Come talk with us!</h1>

    <br/>

    <p class="lead">
      If there is anything we love, it is learning and creating. We would
      really love it if you shared your knowledge and/or your experiences
      with us.
    </p>
  </div>
  <div class="span8">
    <%= render 'form' %>

    <p>
      <small>
        This is nerd focused... Not marketing-focused. Not
        sales-focused. Not recruitment-focused. If you want to talk
        about your company, just make sure you talk
        about <u>using</u> your product. Something we can share.
      </small>
    </p>
  </div>
</div>

<br />

<h1>Proposed Talks</h1>

<% @talks.each_slice(3).each do |row| %>
  <div class="row-fluid">
    <% row.each do |talk| %>
      <div class="proposed_talk span4">
        <h4><%= talk.title %></h4>
        <div><%= indefinite_Articlerize talk.kind %> talk proposed by <%= talk.presenter %></div>
        <p class="description"><%= talk.description %></p>
      </div>
    <% end %>
  </div>
<% end %>

<%= link_to 'Suggest a Topic For a Talk', suggestions_path, {:style => 'font-size 16px; font-weight: bold'} -%>